### ISSUE TITLE
should include --harmony flag?

### ISSUE THREAD

**Issue by aghull** [torontojs/torontojs.com#1]
Interesting. This didn't work for me out of the box until I added the `--harmony` flag to the babel-node start command, which seemed odd to me since I would have assumed that babel-node was always es6 compatible. I think a node_module that gets required needs --harmony in order for the underlying node to handle ES6. Trying to tell the babel-node to `{ ignore: false }` to get babel's magic require replacement to kick in solved some ES6 package issues but seemed to cause a bunch of other ones in the less module that didn't like being forced into strict mode.

**Comment by tazsingh** [comment]
I ran the app off io.js for my presentation but I'm now switching back to Node 0.12 with the `--harmony` flag. I've updated the app accordingly.

**Comment by aghull** [comment]
Ah, right. Forgot you mentioned you were in io.
