### ISSUE TITLE
Deprecated events page?

### ISSUE THREAD

**Issue by MandyMeindersma** [torontojs/torontojs.com#119]
The events page is deprecated right?

should it  re-route to 404 or something then?

https://torontojs.com/events

**Comment by kieran** [comment]
it seems to be serving the blank 404 page from https://github.com/torontojs/torontojs.com/blob/master/public/404.html

maybe what we need is more explicit 404 content?

**Comment by usrrname** [comment]
As this is a discussion question and not a feature, closing

**Comment by MandyMeindersma** [comment]
I don't think this should be closed, I think this needs a more explicit 404 page like @kieran said

**Comment by kieran** [comment]
made a quick 404 page, will add it to my updates PR


https://github.com/torontojs/torontojs.com/assets/3444/aede7483-0c3d-45af-976b-1c90578bbf3c

**Comment by usrrname** [comment]
> As this is a discussion question and not a feature, closing

Sorry about closing it, there's been a ton of stale stuff here since 2017/19 I've been trying to just whittle down. Feel fee to create a PR or make an issue for improvement!
