### ISSUE TITLE
Deprecated Events page

### ISSUE THREAD

**Issue by MandyMeindersma** [torontojs/torontojs.com#138]
The events page has been deprecated for a while

AC:
- It should re-route to a 404 page
- ~The old events code should be deleted~

https://torontojs.com/events

**Comment by kieran** [comment]
The old events code has been deleted afaik, 404 page is waiting to be deployed in this PR: https://github.com/torontojs/torontojs.com/pull/137

**Comment by MandyMeindersma** [comment]
oh woops you're right
