### ISSUE TITLE
New area for navigation

### ISSUE THREAD

**Issue by mihok** [torontojs/torontojs.com#24]
So, with the addition of #18 and #15, we'll need some way of navigating around.

I don't think having an item in the navigation block for every additional page in existence is necessary. Which makes me think it should not be completely dynamic.  

My proposal is to use a JSON file to define a set of links that we'll display on every page as the main navigation list. Something to the effect of:

```js
{
  "Home": "/",
  "Job Board": "//jobs.torontojs.com",
  "Static Page": "/p/static-page",
  // ...
  // Following the pattern of:
  "Label" : "URI" 
}
```

The question I have left is a UX one. **Where do we display the list of links?**

**Comment by JelaniThompson** [comment]
@mihok Maybe something along the lines of [react-burger-menu](http://negomi.github.io/react-burger-menu/)?

**Comment by alex-wilmer** [comment]
@JelaniThompson neat lib! 👍

**Comment by mihok** [comment]
Cool library @JelaniThompson! I wish it worked for the top rather than the left or right. My concern is with the current layout I dont see how it could fit in.

How were you thinking of it? Id love to explore it a little bit, either way I think you should take on this ticket :)

**Comment by JelaniThompson** [comment]
![javascript-dab](https://cloud.githubusercontent.com/assets/11928206/25318445/11bed384-285d-11e7-976f-0ad618903fdb.png)

I was thinking that we could have a white burger menu in the top left where the Slack icon is and somehow put all the community links together in a row as just icons without text beside them in another spot.

If we were to lay things out like that, though, there's plenty of unused space beneath the automated typing where we could potentially put the community links.

That's just my suggestion though. I'd be happy to take on the ticket and implement someone else's design decisions if you think it would be a better fit!

@mihok @alex-wilmer

**Comment by alex-wilmer** [comment]
@JelaniThompson I trust your judgment on this if you have something in mind. want to bikeshed some ideas in a PR then we can discuss? or would you prefer a specific design to follow?

**Comment by JelaniThompson** [comment]
@alex-wilmer Yeah I'll try out what I had in mind and if it ends up not looking as great as I'd hoped I might end up needing some guidance 😛 I'll let you know how it goes :)

**Comment by mihok** [comment]
I'm not married to any specific opinion right now, a couple things I would like to discuss with this proposal:
- Maybe we have the burger menu on the right side and move the "Contribute to this site" to the left side after the slack link.
- Thoughts on having the burger icon sticky to the top right (or left) corner so it follows when scrolling? If that looks alright, we could have it fade to red once its past the Splash area.

**Comment by JelaniThompson** [comment]
Yeah that might be better actually. I'll add it in and post a screenshot once it's finished up :)

**Comment by JelaniThompson** [comment]
So I'd say I'm 90% finished now. Just gotta add the colour changing burger menu for when you scroll down to the white area.

I did have one question though. When I forked + cloned this I was getting a cutoff with the Slack message unless I zoomed out:
![image](https://cloud.githubusercontent.com/assets/11928206/25321506/22843b9e-287d-11e7-9aad-7199ae8ae4b7.png)

Are any of you guys getting this as well? I moved the GitHub link underneath the Slack one and I'm getting the same issue.

Zoomed out:
![image](https://cloud.githubusercontent.com/assets/11928206/25321534/54194e92-287d-11e7-8ee4-df27c4223a1f.png)

**Comment by alex-wilmer** [comment]
@JelaniThompson zIndex issue. fixed here: https://github.com/torontojs/torontojs.com/commit/92af0f7f441dc060a1196ac3547b87f2d6a4c205

rebase and you should be good to go

**Comment by JelaniThompson** [comment]
Thanks Alex!

**Comment by kieran** [comment]
closing since this is very old
