### ISSUE TITLE
Configure Website to allow Linking from YouTube page

### ISSUE THREAD

**Issue by tazsingh** [torontojs/torontojs.com#26]
Collaborate with @teesloane on what's needed to approve torontojs.com for display on the YouTube brand channel. A few options are Google Analytics which I can provide a tracking ID for.

**Comment by teesloane** [comment]
@tazsingh Do you mean to be able to make our videos link to torontojs.com ?

**Comment by tazsingh** [comment]
@teesloane I mean the "Associated Website" in the "Advanced Settings" page needs some approval - https://www.youtube.com/advanced_settings

IMO might be best long term to add Google Analytics which would also solve this. I'll create another Issue and link to this one.
