### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by tazsingh** [torontojs/torontojs.com#27]
I've used this nifty library in the past after setting up the usual `analytics.js` stuff - https://github.com/googleanalytics/autotrack

Tracking ID - `UA-70285153-1`

**Comment by tazsingh** [comment]
Once this is done, YouTube can verify the website to also fix #26

**Comment by teesloane** [comment]
Still not sure if we're on the same page.

On going to youtube I see this:

<img width="577" alt="screenshot 2017-04-23 22 10 02" src="https://cloud.githubusercontent.com/assets/12987958/25320103/163b88d4-2872-11e7-941c-9693adab4ce6.png">

so I click 'verify' and end up here - but am not sure where to put in  the tracking id? 

<img width="749" alt="screenshot 2017-04-23 22 13 06" src="https://cloud.githubusercontent.com/assets/12987958/25320100/0f5ee358-2872-11e7-90cb-b57373a58c9d.png">

I think you might need to get into youtube and login through godaddy to verify...

**Comment by tazsingh** [comment]
Adding Google Analytics is a task for the website. Once it's added to TorontoJS.com, then you can verify it on YouTube.

Not worth mucking around with the other options when we want to add GA anyway.

Does that make sense?

Looks like I may have to click the actual Verify button though as it needs certain permissions to Verify. But one thing at a time!

**Comment by teesloane** [comment]
You got it, sounds good.

**Comment by usrrname** [comment]
Closing stale issue
