### ISSUE TITLE
prettier?

### ISSUE THREAD

**Issue by alex-wilmer** [torontojs/torontojs.com#30]
anyone have opinions / experience? seems like a good standard for open source stuff. hoping to have a meaningful discussion here.

**Comment by mihok** [comment]
Can you give a little context? Do you want to make the site prettier? or ... ?

**Comment by alex-wilmer** [comment]
Oh! Sorry I meant the code formatter https://github.com/prettier/prettier

**Comment by alex-wilmer** [comment]
It's been gaining a lot of popularity lately. Been hearing lots of chatter about it in the torontojs slack as well. Many people have opinions there

**Comment by teesloane** [comment]
Been using it! I like it a lot. Works great with react too.

**Comment by tazsingh** [comment]
Do it
