### ISSUE TITLE
continuous integration

### ISSUE THREAD

**Issue by alex-wilmer** [torontojs/torontojs.com#31]
Would be great to have PR feedback + automatic deploys on merges to master.

I have experience with Travis and its free for public repos so going with that for now. Open to suggestions

**Comment by mihok** [comment]
👍 for Travis

**Comment by alex-wilmer** [comment]
https://github.com/torontojs/torontojs.com/commit/d5f6c22379830d2d8b2895ca53f66a1b21d128be
