### ISSUE TITLE
`yarn start` returns different eslint results than `eslint src`

### ISSUE THREAD

**Issue by mihok** [torontojs/torontojs.com#37]
I found this after working on #21 PR. There are different results spit out when running `yarn start` to what spits out running `eslint src`

Some errors are not reported with `yarn start` and then people may forget to run `eslint src` separately, finally getting a surprise when they make a PR

**Comment by tazsingh** [comment]
We should use the `eslint-loader` in Webpack to report these ESLint errors via Webpack as well.

**Comment by alex-wilmer** [comment]
let's see if we can make that work without ejecting the webpack config first. I can look into it

**Comment by kieran** [comment]
not applicable anymore
