### ISSUE TITLE
Toronto Js Code of Conduct / values etc

### ISSUE THREAD

**Issue by teesloane** [torontojs/torontojs.com#41]
After discussing with @mihok and @dxnn the idea of a code of conduct / values / general knowledges stuffs could fit right in, as a repo, in our organization. Let's collect some ideas and think about what we believe in, represent, love and make, and put it in a place where anyone can contribute and all that.

**Links to consider?**
  - https://www.recurse.com/manual#sub-sec-social-rules
  - http://bangbangcon.com/conduct.html

**Comment by alex-wilmer** [comment]
http://torontojs.com/p/code_of_conduct

fill in here: https://github.com/torontojs/torontojs.com/blob/master/public/pages/code_of_conduct.md

**Comment by mihok** [comment]
This is completed https://torontojs.com/p/code_of_conduct
