### ISSUE TITLE
Add link to the YouTube channel, for users to find it from the site.

### ISSUE THREAD

**Issue by agmcleod** [torontojs/torontojs.com#49]
https://www.youtube.com/channel/UC1samyyfqiKmOT6fq3uVO1A

Can add this on the home page somewhere maybe?

**Comment by bkd705** [comment]
What about under the existing "Join us on slack" link?

We could use one of the white youtube icons to keep the icon stuff consistant?

Like this but white.
![youtube logo](https://www.youtube.com/yt/about/media/images/brand-resources/icons/YouTube_icon_light.svg)

**Comment by alex-wilmer** [comment]
under 'join slack' seems good to me. could also use the fontawesome icon, would be easy to style http://fontawesome.io/icon/youtube-play/

**Comment by bkd705** [comment]
Ahh, perfect! Unless someone else can do it before, I will do it this evening!

**Comment by alex-wilmer** [comment]
something like this maybe?

![image](https://user-images.githubusercontent.com/2880089/30187350-4b480d72-93f7-11e7-86d7-817fcceed748.png)

**Comment by bkd705** [comment]
Do you already have this completed @alex-wilmer or was that just a quick mockup?

**Comment by alex-wilmer** [comment]
i have it in code. if we like it i can push it
