### ISSUE TITLE
Netlify

### ISSUE THREAD

**Issue by alex-wilmer** [torontojs/torontojs.com#54]
github pages is **great**, but netlify is 🔥🔥🔥🔥🔥🔥

@tazsingh are you still the man to ask about dns?

**Comment by tazsingh** [comment]
Thanks @alex-wilmer! Actually transferred the domain over to @pauldowman now. Can ask him to configure this accordingly :)

**Comment by pauldowman** [comment]
@alex-wilmer Are you proposing to do the work? Maybe this is something we could do at the next Code Club night?

**Comment by alex-wilmer** [comment]
@pauldowman there's no work involved, it's just changing the dns from github pages to netlify. do you have a preferred email address? I'll add you as a netlify admin

**Comment by usrrname** [comment]
Seems like @kieran is da netlify host owner now, closing this issue
