### ISSUE TITLE
button for importing events into own calendar

### ISSUE THREAD

**Issue by alex-wilmer** [torontojs/torontojs.com#59]

**Comment by mding5692** [comment]
Is this something that still needs to be worked on? Would it be ok to import components from a library like below:
https://jasonsalzman.github.io/react-add-to-calendar/
http://leibowitz.me/react-add-to-calendar-hoc/docs/

and use that component for this issue?

**Comment by andreidobrinski** [comment]
I can take a look at this! Thanks for the tip @mding5692 , I'll look into those packages

**Comment by usrrname** [comment]
Everything seems to have been moved to Guild for website calendar events... closing; feel free to reopen with new issue/PR for improvements!
