### ISSUE TITLE
Consider moving to different architecture

### ISSUE THREAD

**Issue by alex-wilmer** [torontojs/torontojs.com#7]
I know this is a place you've been experimenting with libraries and I think that's cool. However I was wondering if it made sense to move to some of the awesome libs that exist today to facilitate the ease of maintenance.

Stuff like: 

https://github.com/zeit/next.js/
https://phenomic.io/
https://github.com/relax/relax

Or at the very least update some stuff here to newer versions of libraries like react router 4, newer babel etc.

I wasn't feeling super involved before but I'm wanting to take this on if it's up for grabs. I had a meeting with @dxnn and I have some ideas for using this site to add more info for JS workshop (past events, user feedback, call for speakers, linking / posting creations made by workshop attendees)

Let me know what you think.

Cheers
A

**Comment by tazsingh** [comment]
Of course! Go ahead @alex-wilmer. Just gave you push access!
