### ISSUE TITLE
New area for "sponsored events"

### ISSUE THREAD

**Issue by dxnn** [torontojs/torontojs.com#9]
We're going to start allowing non-free events into the upcoming event list as Sponsored Events, which are paid listings. We need to distinguish these in some way from the regular events: perhaps by color/label, perhaps in a second column, perhaps some other way. 

We also need a way to enter and remove the events. We can do this manually in the short term, we just need a place to put the html and a small template. We can get fancy later with some type of DB integration but it's going to be a handful of events that change once per month, so the manual overhead is very small.

**Comment by alex-wilmer** [comment]
I just copied and pasted what @tazsingh had before basically

https://github.com/torontojs/torontojs.com/blob/master/src/data/events.js

re: adding / removing

do you mean something other than these sources? like a hardcoded list in the repo or pull from a gist or something?

**Comment by dxnn** [comment]
Yep, this is new functionality that we're adding. A hardcoded list of events in one of the files in the repo is fine -- whatever is lowest friction from a dev point of view.

**Comment by alex-wilmer** [comment]
https://github.com/torontojs/torontojs.com/commit/89f19fbf12e8b080ec65018d52a79b54b80f6255

**Comment by dxnn** [comment]
Alex, did you mean to close the Safari one instead? #8

**Comment by alex-wilmer** [comment]
I sure did! 😛

**Comment by usrrname** [comment]
We have an email for that, that goes to directors: `sponsor@torontojs.com` our open collective is up: https://opencollective.com/torontojs
