### ISSUE TITLE
Use `main` as default branch

### ISSUE THREAD

**Issue by usrrname** [torontojs/torontojs.com#96]
Created a `main` branch and would like to transition to that as the default branch.

Anything required or missing to do so?

**Comment by kieran** [comment]
would have to update the netlify integration to watch the main branch, but everything else should work as-is

**Comment by evert** [comment]
I don't have access but the best way to migrate to main is to use the rename main branch feature in GH, as it will update lots of other references too.

**Comment by usrrname** [comment]
> I don't have access but the best way to migrate to main is to use the rename main branch feature in GH, as it will update lots of other references too. 

You now do :)

**Comment by kieran** [comment]
renamed, updated netlify as well
